#!/bin/bash

#########################
#    Utility script     #
#########################

# Usage
# ./scripting106
# Select an option: 1
# Filesystem                          Size   Used  Avail Capacity  iused    ifree %iused  Mounted on
# /dev/disk1                         232Gi   66Gi  165Gi    29% 17437164 43311922   29%   /
# devfs                              184Ki  184Ki    0Bi   100%      635        0  100%   /dev
# map -hosts                           0Bi    0Bi    0Bi   100%        0        0  100%   /net
# map auto_home                        0Bi    0Bi    0Bi   100%        0        0  100%   /home
# localhost:/9_etQ-kO7896TEjsBNaZJD  232Gi  232Gi    0Bi   100%        0        0  100%   /Volumes/MobileBackups
# 1. Show disk usage
# 2. Show uptime
# 3. Show logged users
# 4. q for quit
# Select an option: 2
# 22:49  up 1 day, 23:29, 2 users, load averages: 0.83 1.01 1.13
# 1. Show disk usage
# 2. Show uptime
# 3. Show logged users
# 4. q for quit
# Select an option: 3
# abpatwar console  May 27 23:21
# abpatwar ttys001  May 29 22:21
# 1. Show disk usage
# 2. Show uptime
# 3. Show logged users
# 4. q for quit
# Select an option: q
# $ ./scripting106
# 1. Show disk usage
# 2. Show uptime
# 3. Show logged users
# 4. q for quit
# Select an option: q
# Goodbye!

while true
do
    echo "1. Show disk usage"
    echo "2. Show uptime"
    echo "3. Show logged users"
    echo "4. q for quit"
    read -p "Select an option: " OPTION
    case $OPTION in
        1) df -h;;
        2) uptime;;
        3) who;;
        q) echo "Goodbye!"; exit 0;;
        *) echo "Invalid option";;
    esac
done

           
