#!/bin/bash

case $1 in
    start)
        /tmp/sleep-walking-server &
        exit 0;;
    stop)
        kill $(cat /tmp/sleep-walking-server.pid)
        exit 0;;
    *)
        echo "Usage sleep-walking start|stop"
        exit 1;;
esac
                
          
